name: Build Kernel
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make flex bison libncurses-dev libssl-dev bc git
      - name: Run build
        run: bash build-kernel.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: linux-mt6762/arch/arm64/boot/
